"""initial_schema

Revision ID: afc6c85d43ae
Revises: 
Create Date: 2025-12-16 16:11:15.542179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afc6c85d43ae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflows',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'deployed')", name='ck_workflow_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_steps',
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('context_type', sa.String(length=20), nullable=True),
    sa.Column('context_image_url', sa.String(length=500), nullable=True),
    sa.Column('context_text_content', sa.Text(), nullable=True),
    sa.Column('context_voice_transcript', sa.Text(), nullable=True),
    sa.Column('context_description', sa.Text(), nullable=True),
    sa.Column('extraction_keywords', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('extraction_voice_transcript', sa.Text(), nullable=True),
    sa.Column('logic_strategy', sa.String(length=20), nullable=True),
    sa.Column('logic_rule_expression', sa.Text(), nullable=True),
    sa.Column('logic_evaluation_prompt', sa.Text(), nullable=True),
    sa.Column('routing_default_next', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("context_type IS NULL OR context_type IN ('image', 'text', 'voice')", name='ck_context_type'),
    sa.CheckConstraint("logic_strategy IS NULL OR logic_strategy IN ('rule_based', 'few_shot')", name='ck_logic_strategy'),
    sa.CheckConstraint("status IN ('pending', 'completed')", name='ck_step_status'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'step_order', name='uq_workflow_step_order')
    )
    op.create_table('examples',
    sa.Column('step_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=True),
    sa.Column('label', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("content_type IS NULL OR content_type IN ('image', 'text')", name='ck_example_content_type'),
    sa.CheckConstraint("label IN ('PASS', 'FAIL')", name='ck_example_label'),
    sa.ForeignKeyConstraint(['step_id'], ['workflow_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routing_branches',
    sa.Column('step_id', sa.UUID(), nullable=False),
    sa.Column('condition_result', sa.String(length=100), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('next_step_id', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['step_id'], ['workflow_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # Create indexes for better query performance
    op.create_index('idx_workflow_steps_workflow_id', 'workflow_steps', ['workflow_id'])
    op.create_index('idx_examples_step_id', 'examples', ['step_id'])
    op.create_index('idx_routing_branches_step_id', 'routing_branches', ['step_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes first
    op.drop_index('idx_routing_branches_step_id', 'routing_branches')
    op.drop_index('idx_examples_step_id', 'examples')
    op.drop_index('idx_workflow_steps_workflow_id', 'workflow_steps')
    # Drop tables
    op.drop_table('routing_branches')
    op.drop_table('examples')
    op.drop_table('workflow_steps')
    op.drop_table('workflows')
    # ### end Alembic commands ###
