"""Pydantic Schemas for API request/response."""

from app.schemas.base import BaseSchema, IDMixin, TimestampMixin
from app.schemas.protocol import (
    ProtocolFewShotExample,
    ProtocolInputSpec,
    ProtocolLogicConfig,
    ProtocolLogicStrategy,
    ProtocolOutputField,
    ProtocolOutputSchema,
    ProtocolRoutingBranch,
    ProtocolRoutingMap,
    ProtocolStep,
    ProtocolWorkflow,
)
from app.schemas.workflow import (
    ContentType,
    ContextData,
    ContextType,
    ExampleBase,
    ExampleCreate,
    ExampleLabel,
    ExampleResponse,
    ExampleUpdate,
    ExtractionData,
    LogicData,
    LogicStrategy,
    RoutingBranchBase,
    RoutingBranchCreate,
    RoutingBranchResponse,
    RoutingBranchUpdate,
    RoutingData,
    StepStatus,
    WorkflowBase,
    WorkflowCreate,
    WorkflowListResponse,
    WorkflowResponse,
    WorkflowStatus,
    WorkflowStepBase,
    WorkflowStepCreate,
    WorkflowStepResponse,
    WorkflowStepSummary,
    WorkflowStepUpdate,
    WorkflowSummary,
    WorkflowUpdate,
)

__all__ = [
    # Base
    "BaseSchema",
    "IDMixin",
    "TimestampMixin",
    # Workflow
    "WorkflowStatus",
    "StepStatus",
    "ContextType",
    "LogicStrategy",
    "ContentType",
    "ExampleLabel",
    "WorkflowBase",
    "WorkflowCreate",
    "WorkflowUpdate",
    "WorkflowResponse",
    "WorkflowSummary",
    "WorkflowListResponse",
    # WorkflowStep
    "WorkflowStepBase",
    "WorkflowStepCreate",
    "WorkflowStepUpdate",
    "WorkflowStepResponse",
    "WorkflowStepSummary",
    # Micro-step data
    "ContextData",
    "ExtractionData",
    "LogicData",
    "RoutingData",
    # Example
    "ExampleBase",
    "ExampleCreate",
    "ExampleUpdate",
    "ExampleResponse",
    # RoutingBranch
    "RoutingBranchBase",
    "RoutingBranchCreate",
    "RoutingBranchUpdate",
    "RoutingBranchResponse",
    # Protocol
    "ProtocolLogicStrategy",
    "ProtocolInputSpec",
    "ProtocolFewShotExample",
    "ProtocolLogicConfig",
    "ProtocolRoutingBranch",
    "ProtocolRoutingMap",
    "ProtocolOutputField",
    "ProtocolOutputSchema",
    "ProtocolStep",
    "ProtocolWorkflow",
]
